/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedOrgRouteRouteImport } from './routes/_authenticated/_org/route'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedOrgCopilotRouteImport } from './routes/_authenticated/_org/copilot'
import { Route as AuthenticatedOrgDashboardRouteImport } from './routes/_authenticated/_org/dashboard'
import { Route as AuthenticatedOrgDemandRouteImport } from './routes/_authenticated/_org/demand'
import { Route as AuthenticatedOrgImpactRouteImport } from './routes/_authenticated/_org/impact'
import { Route as AuthenticatedOrgMenuRouteImport } from './routes/_authenticated/_org/menu'
import { Route as AuthenticatedOrgRecipientsRouteImport } from './routes/_authenticated/_org/recipients'
import { Route as AuthenticatedOrgSafetyRouteImport } from './routes/_authenticated/_org/safety'
import { Route as AuthenticatedOrgServiceDayRouteImport } from './routes/_authenticated/_org/service-day'
import { Route as AuthenticatedOrgSettingsRouteImport } from './routes/_authenticated/_org/settings'
import { Route as AuthenticatedOrgSurplusRouteImport } from './routes/_authenticated/_org/surplus'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOrgRouteRoute = AuthenticatedOrgRouteRouteImport.update({
  id: '/_org',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOrgCopilotRoute = AuthenticatedOrgCopilotRouteImport.update({
  id: '/copilot',
  path: '/copilot',
  getParentRoute: () => AuthenticatedOrgRouteRoute,
} as any)
const AuthenticatedOrgDashboardRoute =
  AuthenticatedOrgDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedOrgRouteRoute,
  } as any)
const AuthenticatedOrgDemandRoute = AuthenticatedOrgDemandRouteImport.update({
  id: '/demand',
  path: '/demand',
  getParentRoute: () => AuthenticatedOrgRouteRoute,
} as any)
const AuthenticatedOrgImpactRoute = AuthenticatedOrgImpactRouteImport.update({
  id: '/impact',
  path: '/impact',
  getParentRoute: () => AuthenticatedOrgRouteRoute,
} as any)
const AuthenticatedOrgMenuRoute = AuthenticatedOrgMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => AuthenticatedOrgRouteRoute,
} as any)
const AuthenticatedOrgRecipientsRoute =
  AuthenticatedOrgRecipientsRouteImport.update({
    id: '/recipients',
    path: '/recipients',
    getParentRoute: () => AuthenticatedOrgRouteRoute,
  } as any)
const AuthenticatedOrgSafetyRoute = AuthenticatedOrgSafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => AuthenticatedOrgRouteRoute,
} as any)
const AuthenticatedOrgServiceDayRoute =
  AuthenticatedOrgServiceDayRouteImport.update({
    id: '/service-day',
    path: '/service-day',
    getParentRoute: () => AuthenticatedOrgRouteRoute,
  } as any)
const AuthenticatedOrgSettingsRoute =
  AuthenticatedOrgSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedOrgRouteRoute,
  } as any)
const AuthenticatedOrgSurplusRoute = AuthenticatedOrgSurplusRouteImport.update({
  id: '/surplus',
  path: '/surplus',
  getParentRoute: () => AuthenticatedOrgRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/copilot': typeof AuthenticatedOrgCopilotRoute
  '/dashboard': typeof AuthenticatedOrgDashboardRoute
  '/demand': typeof AuthenticatedOrgDemandRoute
  '/impact': typeof AuthenticatedOrgImpactRoute
  '/menu': typeof AuthenticatedOrgMenuRoute
  '/recipients': typeof AuthenticatedOrgRecipientsRoute
  '/safety': typeof AuthenticatedOrgSafetyRoute
  '/service-day': typeof AuthenticatedOrgServiceDayRoute
  '/settings': typeof AuthenticatedOrgSettingsRoute
  '/surplus': typeof AuthenticatedOrgSurplusRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/copilot': typeof AuthenticatedOrgCopilotRoute
  '/dashboard': typeof AuthenticatedOrgDashboardRoute
  '/demand': typeof AuthenticatedOrgDemandRoute
  '/impact': typeof AuthenticatedOrgImpactRoute
  '/menu': typeof AuthenticatedOrgMenuRoute
  '/recipients': typeof AuthenticatedOrgRecipientsRoute
  '/safety': typeof AuthenticatedOrgSafetyRoute
  '/service-day': typeof AuthenticatedOrgServiceDayRoute
  '/settings': typeof AuthenticatedOrgSettingsRoute
  '/surplus': typeof AuthenticatedOrgSurplusRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/_org': typeof AuthenticatedOrgRouteRouteWithChildren
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/_org/copilot': typeof AuthenticatedOrgCopilotRoute
  '/_authenticated/_org/dashboard': typeof AuthenticatedOrgDashboardRoute
  '/_authenticated/_org/demand': typeof AuthenticatedOrgDemandRoute
  '/_authenticated/_org/impact': typeof AuthenticatedOrgImpactRoute
  '/_authenticated/_org/menu': typeof AuthenticatedOrgMenuRoute
  '/_authenticated/_org/recipients': typeof AuthenticatedOrgRecipientsRoute
  '/_authenticated/_org/safety': typeof AuthenticatedOrgSafetyRoute
  '/_authenticated/_org/service-day': typeof AuthenticatedOrgServiceDayRoute
  '/_authenticated/_org/settings': typeof AuthenticatedOrgSettingsRoute
  '/_authenticated/_org/surplus': typeof AuthenticatedOrgSurplusRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/copilot'
    | '/dashboard'
    | '/demand'
    | '/impact'
    | '/menu'
    | '/recipients'
    | '/safety'
    | '/service-day'
    | '/settings'
    | '/surplus'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/copilot'
    | '/dashboard'
    | '/demand'
    | '/impact'
    | '/menu'
    | '/recipients'
    | '/safety'
    | '/service-day'
    | '/settings'
    | '/surplus'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/_org'
    | '/_authenticated/onboarding'
    | '/_authenticated/_org/copilot'
    | '/_authenticated/_org/dashboard'
    | '/_authenticated/_org/demand'
    | '/_authenticated/_org/impact'
    | '/_authenticated/_org/menu'
    | '/_authenticated/_org/recipients'
    | '/_authenticated/_org/safety'
    | '/_authenticated/_org/service-day'
    | '/_authenticated/_org/settings'
    | '/_authenticated/_org/surplus'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_org': {
      id: '/_authenticated/_org'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedOrgRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/_org/copilot': {
      id: '/_authenticated/_org/copilot'
      path: '/copilot'
      fullPath: '/copilot'
      preLoaderRoute: typeof AuthenticatedOrgCopilotRouteImport
      parentRoute: typeof AuthenticatedOrgRouteRoute
    }
    '/_authenticated/_org/dashboard': {
      id: '/_authenticated/_org/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedOrgDashboardRouteImport
      parentRoute: typeof AuthenticatedOrgRouteRoute
    }
    '/_authenticated/_org/demand': {
      id: '/_authenticated/_org/demand'
      path: '/demand'
      fullPath: '/demand'
      preLoaderRoute: typeof AuthenticatedOrgDemandRouteImport
      parentRoute: typeof AuthenticatedOrgRouteRoute
    }
    '/_authenticated/_org/impact': {
      id: '/_authenticated/_org/impact'
      path: '/impact'
      fullPath: '/impact'
      preLoaderRoute: typeof AuthenticatedOrgImpactRouteImport
      parentRoute: typeof AuthenticatedOrgRouteRoute
    }
    '/_authenticated/_org/menu': {
      id: '/_authenticated/_org/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof AuthenticatedOrgMenuRouteImport
      parentRoute: typeof AuthenticatedOrgRouteRoute
    }
    '/_authenticated/_org/recipients': {
      id: '/_authenticated/_org/recipients'
      path: '/recipients'
      fullPath: '/recipients'
      preLoaderRoute: typeof AuthenticatedOrgRecipientsRouteImport
      parentRoute: typeof AuthenticatedOrgRouteRoute
    }
    '/_authenticated/_org/safety': {
      id: '/_authenticated/_org/safety'
      path: '/safety'
      fullPath: '/safety'
      preLoaderRoute: typeof AuthenticatedOrgSafetyRouteImport
      parentRoute: typeof AuthenticatedOrgRouteRoute
    }
    '/_authenticated/_org/service-day': {
      id: '/_authenticated/_org/service-day'
      path: '/service-day'
      fullPath: '/service-day'
      preLoaderRoute: typeof AuthenticatedOrgServiceDayRouteImport
      parentRoute: typeof AuthenticatedOrgRouteRoute
    }
    '/_authenticated/_org/settings': {
      id: '/_authenticated/_org/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedOrgSettingsRouteImport
      parentRoute: typeof AuthenticatedOrgRouteRoute
    }
    '/_authenticated/_org/surplus': {
      id: '/_authenticated/_org/surplus'
      path: '/surplus'
      fullPath: '/surplus'
      preLoaderRoute: typeof AuthenticatedOrgSurplusRouteImport
      parentRoute: typeof AuthenticatedOrgRouteRoute
    }
  }
}

interface AuthenticatedOrgRouteRouteChildren {
  AuthenticatedOrgCopilotRoute: typeof AuthenticatedOrgCopilotRoute
  AuthenticatedOrgDashboardRoute: typeof AuthenticatedOrgDashboardRoute
  AuthenticatedOrgDemandRoute: typeof AuthenticatedOrgDemandRoute
  AuthenticatedOrgImpactRoute: typeof AuthenticatedOrgImpactRoute
  AuthenticatedOrgMenuRoute: typeof AuthenticatedOrgMenuRoute
  AuthenticatedOrgRecipientsRoute: typeof AuthenticatedOrgRecipientsRoute
  AuthenticatedOrgSafetyRoute: typeof AuthenticatedOrgSafetyRoute
  AuthenticatedOrgServiceDayRoute: typeof AuthenticatedOrgServiceDayRoute
  AuthenticatedOrgSettingsRoute: typeof AuthenticatedOrgSettingsRoute
  AuthenticatedOrgSurplusRoute: typeof AuthenticatedOrgSurplusRoute
}

const AuthenticatedOrgRouteRouteChildren: AuthenticatedOrgRouteRouteChildren = {
  AuthenticatedOrgCopilotRoute: AuthenticatedOrgCopilotRoute,
  AuthenticatedOrgDashboardRoute: AuthenticatedOrgDashboardRoute,
  AuthenticatedOrgDemandRoute: AuthenticatedOrgDemandRoute,
  AuthenticatedOrgImpactRoute: AuthenticatedOrgImpactRoute,
  AuthenticatedOrgMenuRoute: AuthenticatedOrgMenuRoute,
  AuthenticatedOrgRecipientsRoute: AuthenticatedOrgRecipientsRoute,
  AuthenticatedOrgSafetyRoute: AuthenticatedOrgSafetyRoute,
  AuthenticatedOrgServiceDayRoute: AuthenticatedOrgServiceDayRoute,
  AuthenticatedOrgSettingsRoute: AuthenticatedOrgSettingsRoute,
  AuthenticatedOrgSurplusRoute: AuthenticatedOrgSurplusRoute,
}

const AuthenticatedOrgRouteRouteWithChildren =
  AuthenticatedOrgRouteRoute._addFileChildren(
    AuthenticatedOrgRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedOrgRouteRoute: typeof AuthenticatedOrgRouteRouteWithChildren
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedOrgRouteRoute: AuthenticatedOrgRouteRouteWithChildren,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
